export { createSupabaseClient, getSupabaseClient } from './client';
export {
  createSessionFromUrl,
  getAuthErrorMessage,
  resetPasswordForEmail,
  signInWithApple,
  signInWithEmail,
  signInWithGoogle,
  signOut,
  signUpWithEmail,
  deleteAccount,
} from './auth';
export {
  completeClinicSetup,
  getClinicProfile,
  getMissingClinicProfileFields,
  isClinicProfileComplete,
  upsertClinicProfile,
  type ClinicProfile,
  type ClinicProfileUpdate,
} from './clinicProfile';
export { parseMapboxFeature, searchAddresses, type AddressSuggestion, type ParsedAddress } from './mapbox';
export {
  createJobPost,
  createShiftPost,
  deleteJobPost,
  deleteShiftPost,
  getClinicDashboardCounts,
  getJobPost,
  getJobPostApplicationCount,
  getShiftPost,
  getShiftPostApplicationCount,
  getLiveJobPost,
  getLiveShiftPost,
  getWorkerDashboardCounts,
  listLiveJobPosts,
  listLiveShiftPosts,
  listJobPosts,
  listShiftPosts,
  updateJobPost,
  updateJobPostStatus,
  updateShiftPost,
  updateShiftPostStatus,
  type ClinicDashboardCounts,
  type ClinicSummary,
  type CreateJobPostInput,
  type CreateShiftPostInput,
  type EmploymentType,
  type JobPost,
  type JobPostStatus,
  type LiveJobPost,
  type LiveShiftPost,
  type PostStatus,
  type RoleType,
  type ShiftPost,
  type ShiftPostStatus,
  type ShiftUrgency,
  type UpdateJobPostInput,
  type UpdateShiftPostInput,
  type WorkerDashboardCounts,
} from './posts';
export {
  completeWorkerSetup,
  getMissingWorkerProfileFields,
  getWorkerProfile,
  getWorkerProfileForClinic,
  isWorkerProfileComplete,
  listAvailabilityBlocks,
  upsertAvailabilityBlocks,
  upsertWorkerProfile,
  type AvailabilityBlock,
  type AvailabilityBlockInput,
  type FillInNotificationMode,
  type WorkerProfile,
  type WorkerProfileUpdate,
} from './workerProfile';
export {
  createApplication,
  hasAppliedToJob,
  hasAppliedToShift,
  listClinicApplications,
  listWorkerApplications,
  updateApplicationStatus,
  type Application,
  type ApplicationStatus,
  type ClinicApplication,
  type CreateApplicationInput,
  type WorkerApplication,
} from './applications';
export { getProfile, setProfileRole, updateProfileDisplayName } from './profile';
export type { Database, Profile, UserRole } from './types';
